### ISSUE TITLE
How to use "--input-size" properly?

### ISSUE THREAD

**Issue by Tanelmina** [NVlabs/GCVit#44]
Hi! 
I'm probably doing something fundamentally wrong when I try to train the model in a slightly different input size. 
For example 

python train.py --config configs/gc_vit_large.yml --data_dir '/mnt/…/my/custom/dataset/' --num-classes 17 --no-aug --crop-pct 1 --input-size 3 384 384 --experiment dif_InputSize

gives me the following error: 

Traceback (most recent call last):
  File "train.py", line 864, in <module>
    main()
  File "train.py", line 648, in main
    train_metrics = train_one_epoch(
  File "train.py", line 722, in train_one_epoch
    output = model(input)
  File "/home/tan/env-GCVit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tan/GCVit/models/gc_vit.py", line 705, in forward
    x = self.forward_features(x)
  File "/home/tan/GCVit/models/gc_vit.py", line 696, in forward_features
    x = level(x)
  File "/home/tan/env-GCVit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tan/GCVit/models/gc_vit.py", line 600, in forward
    q_global = self.q_global_gen(_to_channel_first(x))
  File "/home/tan/env-GCVit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tan/GCVit/models/gc_vit.py", line 536, in forward
    x = x.reshape(B, 1, self.N, self.num_heads, self.dim_head).permute(0, 1, 3, 2, 4)
RuntimeError: shape '[32, 1, 49, 6, 32]' is invalid for input of size 884736

If you could explain what I'm doing wrong here and how can I fix it, that would be great.

**Comment by ahatamiz** [comment]
Hi @Tanelmina 

This error is typically due to using an image input size that would not be divisible by the chosen window sizes. I will add some support for adding arbitrary input sizes later.

**Comment by ahatamiz** [comment]
We have added the [detection code](https://github.com/NVlabs/GCVit/tree/main/detection) which supports arbitrary resolutions (multi-scale training). Hopefully this can be useful
